name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: FundMe CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Dependencies
        run: |
          forge install cyfrin/foundry-devops@0.2.2 --no-commit
          forge install smartcontractkit/chainlink-brownie-contracts@1.1.1 --no-commit
          forge install foundry-rs/forge-std@v1.8.2 --no-commit

      - name: Verify Remappings
        run: |
          forge remappings

      - name: Show Forge Version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
